### ISSUE TITLE
RPC method not implemented /wechaty.Puppet/MessageForward

### ISSUE THREAD

**Issue by secreter** [wechaty/puppet-service#187]
puppet：puppet_donut

```
└─┬ wechaty@1.9.5
  └── wechaty-puppet-service@1.7.3 
```
```
exception: Error: 12 UNIMPLEMENTED: RPC method not implemented /wechaty.Puppet/MessageForward
(node:77678) UnhandledPromiseRejectionWarning: Error: 12 UNIMPLEMENTED: RPC method not implemented /wechaty.Puppet/MessageForward
    at Object.callErrorFromStatus (/home/ubuntu/robot/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/ubuntu/robot/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
    at Object.onReceiveStatus (/home/ubuntu/robot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/home/ubuntu/robot/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /home/ubuntu/robot/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(node:77678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by huan** [comment]
> exception: Error: 12 UNIMPLEMENTED: RPC method not implemented /wechaty.Puppet/MessageForward

I believe the error message is clear enough: the server lacks the support for this gRPC method.

As far as I know, the [donut](https://wechaty.js.org/docs/puppet-services/donut/) has been sunset already, however, you can try to contact the provider support to see if you can get any help.
