### ISSUE TITLE
UrlLink is not a constructor

### ISSUE THREAD

**Issue by secreter** [wechaty/puppet-service#188]
puppet：puppet_donut

```
└─┬ wechaty@1.9.5
  └── wechaty-puppet-service@1.7.3 
```
```
(node:77678) UnhandledPromiseRejectionWarning: TypeError: UrlLink is not a constructor
    at Object.onText (/lib/common.js:36:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async onRoomMessage (/home/ubuntu/robot/src/listeners/on-room-message.js:48:7)
(node:77678) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by huan** [comment]
See:

- https://github.com/wechaty/wechaty/issues/2301#issuecomment-973892248
