### ISSUE TITLE
'eventName post unsupported' when a CLI-creating gateway service be connented

### ISSUE THREAD

**Issue by WukongZeming** [wechaty/puppet-service#195]

**Comment by WukongZeming** [comment]
the puppet-xp gateway service can be luanched well  by the CLI (wechaty gateway --puppet), however it raise an 'eventName post unsupported' Error and get crushed as soon as been connected.

puppet:puppet-xp
wechaty version：next

the detail Error log as follows:

```
16:25:14 INFO IoClient 晓燕 logged in
16:25:14 WARN PuppetServer start() TLS disabled: INSECURE!
16:29:42 ERR PuppetServiceImpl stop() eventStreamManager is not busy?
16:29:42 WARN PuppetLoginMixin logonoff() is deprecated, use `isLoggedIn` instead:
Error
    at PuppetXp.logonoff (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/wechaty-puppet/dist/esm/src/mixins/login-mixin.js:86:101)
    at PuppetXp.onStop (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/dist/esm/src/puppet-xp.js:203:18)
    at PuppetXp.stop (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/state-switch/dist/esm/src/service-ctl/service-ctl.js:108:28)
    at PuppetXp.stop (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty-puppet-xp/node_modules/wechaty-puppet/dist/esm/src/mixins/service-mixin.js:25:25)
    at stop (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/server/puppet-implementation.js:1085:45)
    at Object.stop (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/auth/auth-impl-token.js:26:28)
    at handleUnary (C:\Users\bigbr\AppData\Roaming\npm\node_modules\wechaty\node_modules\@grpc\grpc-js\build\src\server.js:674:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
16:29:42 INFO IoClient 晓燕 logged out
16:29:42 INFO IoClient 晓燕 logged in
file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/server/event-stream-manager.js:216
                    throw new Error('eventName ' + eventName + ' unsupported!');
                          ^

Error: eventName post unsupported!
    at EventStreamManager.connectPuppetEventToStreamingCall (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/server/event-stream-manager.js:216:27)
    at EventStreamManager.start (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/server/event-stream-manager.js:41:41)
    at event (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/server/puppet-implementation.js:287:32)
    at Object.event (file:///C:/Users/bigbr/AppData/Roaming/npm/node_modules/wechaty/node_modules/wechaty-puppet-service/dist/esm/src/auth/auth-impl-token.js:26:28)
    at handleServerStreaming (C:\Users\bigbr\AppData\Roaming\npm\node_modules\wechaty\node_modules\@grpc\grpc-js\build\src\server.js:696:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by huan** [comment]
Thank you for reporting this problem!

To fix it, please use `wechaty@1.11.42` instead of `wechaty@next` because the `@next` has been upgraded to the `1.13` which is not stable for use.

**Comment by huan** [comment]
It seems that your npm dependencies are mixed with the `next` versions.

Could you please show the output of the following command:

```sh
npm ls wechaty wechaty-puppet wechaty-puppet-service wechaty-puppet-xp
```

**Comment by WukongZeming** [comment]
```
C:\Users\bigbr\AppData\Roaming\npm>npm ls wechaty wechaty-puppet wechaty-puppet-service wechaty-puppet-xp
C:\Users\bigbr\AppData\Roaming\npm
+-- wechaty-puppet-xp@1.10.2 extraneous
| `-- wechaty-puppet@1.10.2 extraneous
`-- wechaty@1.11.42 extraneous
  +-- wechaty-puppet-service@1.11.3 extraneous
  | `-- wechaty-puppet@1.11.17 deduped
  +-- wechaty-puppet-wechat4u@1.11.1 extraneous
  | `-- wechaty-puppet@1.11.17 deduped
  +-- wechaty-puppet@1.11.17 extraneous
  `-- wechaty-redux@1.10.2 extraneous
    `-- wechaty-puppet@1.11.17 deduped
```
thx for your information

**Comment by huan** [comment]
Thanks for the feedback.

From the log, your `wechaty-puppet` has two versions:

1.  wechaty-puppet@1.10.2 extraneous
2. wechaty-puppet@1.11.17 deduped

Can you try to update them to all be `1.11.17`? I believe this version will fix your issue.

**Comment by WukongZeming** [comment]
Thanks for your help.
I've tried updated and find that: with the command `npm install -g wechaty@1.11.42 wechaty-puppet-xp`
you will get only this:
```
+-- wechaty-puppet-xp@1.10.2 extraneous
| `-- wechaty-puppet@1.10.2 extraneous
`-- wechaty@1.11.42 extraneous
  +-- wechaty-puppet-service@1.11.3 extraneous
  | `-- wechaty-puppet@1.11.17 deduped
  +-- wechaty-puppet-wechat4u@1.11.1 extraneous
  | `-- wechaty-puppet@1.11.17 deduped
  +-- wechaty-puppet@1.11.17 extraneous
  `-- wechaty-redux@1.10.2 extraneous
    `-- wechaty-puppet@1.11.17 deduped
```
you can never update the wechaty-puppet belong to wechaty-puppet-xp to the 1.11.17.....

however by other ways, I've finally got:
```
+-- wechaty-puppet-xp@1.10.2 extraneous
| +-- wechaty-puppet-service@1.11.2 extraneous
| | `-- wechaty-puppet@1.11.14 deduped
| +-- wechaty-puppet-xp@1.10.2 extraneous
| | `-- wechaty-puppet@1.11.14 deduped
| +-- wechaty-puppet@1.11.14 extraneous
| +-- wechaty-redux@1.10.2 extraneous
| | `-- wechaty-puppet@1.11.14 deduped
| `-- wechaty@1.11.20 extraneous
|   +-- wechaty-puppet-service@1.11.2 deduped
|   `-- wechaty-puppet@1.11.14 deduped
`-- wechaty@1.11.42 extraneous
  +-- wechaty-puppet-service@1.11.3 extraneous
  | `-- wechaty-puppet@1.11.17 deduped
  +-- wechaty-puppet-wechat4u@1.11.1 extraneous
  | `-- wechaty-puppet@1.11.17 deduped
  +-- wechaty-puppet@1.11.17 extraneous
  `-- wechaty-redux@1.10.2 extraneous
    `-- wechaty-puppet@1.11.17 deduped
```
but the issue remains  'eventName post unsupported'.

so wired...

**Comment by huan** [comment]
Sorry for this version problem.

We will try to fix it in the following `@latest` version

For your current situation, I guess you can try this workaround:

```sh
rm -fr node_modules/wechaty-puppet-xp/node_modules/wechaty-puppet
```

Then try again, it might solve your problem temporary.

**Comment by WukongZeming** [comment]
@huan thx for your  patience. I can run the gateway by CLI again!
it seems puppet-xp has just released a new version and it contains the 1.11.17 wechaty-puppet.
Anyway that's not bad!

I'll  try to write a detail manual to reference how to create a wechaty local gateway serive by the wechaty 1.11.42 CLI.

**Comment by huan** [comment]
It's great to know that the wechaty CLI works for you now!

Looking forward for your manual, I believe it is very valuable because it can help more users, and happy Chinese new year!

**Comment by Dreamkeeper66666** [comment]
> @huan thx for your patience. I can run the gateway by CLI again! it seems puppet-xp has just released a new version and it contains the 1.11.17 wechaty-puppet. Anyway that's not bad!
> 
> I'll try to write a detail manual to reference how to create a wechaty local gateway serive by the wechaty 1.11.42 CLI.

Hi! I got the same problem as yours. So how did you solve it? Where can I get the new version of puppet-xp which contains 1.11.17 wechaty-puppet? Thanks!

**Comment by WukongZeming** [comment]
you can find  the manuel here  【腾讯文档】如何在本地使用免费的wechaty-puppet-xy协议
https://docs.qq.com/doc/DQ0VJUWtSVE1Mb2JJ


Could help to post a PR to: https://github.com/wechaty/wechaty.js.org?
I'm not  familar with github... after some searching, I still have no idea  how to post a PR  in a github website...
