### ISSUE TITLE
Error: no grpc manager

### ISSUE THREAD

**Issue by huan** [wechaty/puppet-service#223]
`wechaty-puppet-service@1.19.9` with Friday BOT:

```sh
03:30:36 VERB Room findAll({"topic":"/Wechaty|BOT/i"})
03:30:36 VERB PuppetRoomMixin roomSearch({"topic":{}})
03:30:36 VERB PuppetService roomList()
03:30:36 INFO WechatyPluginContrib EventLoggerPlugin() error: [{"code":2,"details":"Error: no grpc manager\n    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)\n    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)\n    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)\n    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)\n    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)\n    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)\n    at Generator.next (<anonymous>)\n    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)\n    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)\n    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"no grpc manager","name":"Error","stack":"Error: no grpc manager\n    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)\n    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)\n    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)\n    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)\n    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)\n    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)\n    at Generator.next (<anonymous>)\n    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)\n    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)\n    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}]
GError: no grpc manager
    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)
    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)
    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)
    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)
    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)
    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)
    at Generator.next (<anonymous>)
    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)
    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)
    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'Error: no grpc manager\n' +
    '    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)\n' +
    '    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)\n' +
    '    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)\n' +
    '    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)\n' +
    '    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)\n' +
    '    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)\n' +
    '    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)\n' +
    '    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
03:30:36 ERR on-error onError(Error: no grpc manager)
GError: no grpc manager
    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)
    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)
    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)
    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)
    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)
    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)
    at Generator.next (<anonymous>)
    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)
    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)
    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'Error: no grpc manager\n' +
    '    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)\n' +
    '    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)\n' +
    '    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)\n' +
    '    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)\n' +
    '    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)\n' +
    '    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)\n' +
    '    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)\n' +
    '    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
Error: no grpc manager
    at PuppetService.get grpcManager [as grpcManager] (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:100:13)
    at PuppetService.roomList (file:///home/friday/git/friday/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:1327:12)
    at PuppetService.roomSearch (file:///home/friday/git/friday/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:50)
    at Function.findAll (file:///home/friday/git/friday/node_modules/wechaty/src/user-modules/room.ts:149:52)
    at GetWorkProMembersCountHandler.execute (file:///home/friday/git/friday/src/domains/statuspage/queries/handlers/get-workpro-members-count.handler.ts:46:46)
    at QueryBus.<anonymous> (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:51:42)
    at Generator.next (<anonymous>)
    at /home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:17:71
    at new Promise (<anonymous>)
    at __awaiter (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:13:12)
    at QueryBus.execute (/home/friday/git/friday/node_modules/@nestjs/cqrs/dist/query-bus.js:44:16)
    at CountingService.countCommunityDevelopers (file:///home/friday/git/friday/src/domains/statuspage/counting.service.ts:45:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
03:30:36 VERB Room findAll() rejected: no grpc manager
03:30:36 VERB Room memberList()
03:30:36 VERB PuppetService roomMemberList(R:10696051795072507)
[Nest] 3844184  - 02/12/2023, 3:30:36 AM   ERROR [Scheduler] Error: no grpc manager
03:30:46 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["heartbeat@padlocal"]
03:30:47 VERB check if QR code is scanned (try to login) if not scanned, new QR code will be shown
03:30:47 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["puppeteer still connected"]
03:30:47 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
03:30:47 INFO WechatyPluginContrib EventLoggerPlugin() scan: ["https://txz.qq.com/p?k=Oi3fQVr2lHQLRJ4y-7lUcCBNLAO2GQZl&f=16",2,null]
03:31:01 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["heartbeat@padlocal"]
03:31:02 VERB check if QR code is scanned (try to login) if not scanned, new QR code will be shown
03:31:02 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["puppeteer still connected"]
03:31:02 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
03:31:02 INFO WechatyPluginContrib EventLoggerPlugin() scan: ["https://txz.qq.com/p?k=r94OjlYu4gRsfqjetpm0--PA8AWYcT6z&f=16",2,null]
03:31:16 INFO WechatyPluginContrib EventLoggerPlugin() heartbeat: ["heartbeat@padlocal"]
```

**Comment by huan** [comment]
It happened again yesterday. I guess it's related to a bug from puppet-service with the WorkPro grpc service behavior.

**Comment by wwz223** [comment]
How to fix this error
